---
layout: post
title: "puppeteer와 readline 버그 (1) 190829 TIL"
tags: [TIL, opensource]
---

개인 프로젝트 코드도 손에 잘 안 잡히고, 뭔가 재미있는 게 없는가 해서 puppeteer의 이슈들을 뒤적거리다가 신기한(?) [버그](https://github.com/GoogleChrome/puppeteer/issues/3829)를 발견했다.

```javascript
const puppeteer = require('puppeteer');
const readline = require("readline");
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});
async function main() {
    browser = await puppeteer.launch();
    rl.close();
    await browser.close();  
    console.log("this line will not be executed.");
}
main();
```

readline.Interface의 인스턴스를 만들고 그것을 닫은 다음 브라우저(퍼페티어가 만든)를 닫으려고 시도하면 강제종료 하기 전까지 코드가 영원히 멈추는 버그였다. 
해결방법은 2가지가 있는데, 
1) readline.createInterface()에 옵션으로 terminal: false를 넣어주거나
2) 브라우저를 먼저 닫고 인스턴스를 닫으면 된다. 

인스턴스를 닫았는데 퍼페티어의 브라우저가 영향을 받는 이상한 현상의 원인이 무엇인지 몹시 궁금해서, 나름대로 원인을 찾으려고 노력해보았다. 

### 디버거로 테스트하기

비쥬얼 스튜디오 코드에 있는 디버거로 테스트를 해보았다. 하지만 디버거로는 버그가 재현되지 않았다. 

### console.log는 좋은 친구

하는 수 없이 의심가는 코드 앞뒤로 console.log를 추가해서 계속 돌려가며 어디에서 문제가 발생하는지를 찾아나섰다. 

먼저 `browser.close()`에서 무슨 일이 일어나고 있는지를 보기 위해 Browser.js 파일을 열어보았다. close 메소드를 확인해보니 아래와 같이 2줄로 이루어져 있었다.

```javascript
  async close() {
    this._closeCallback.call(null);
    this.disconnect();
  }
```
console.log를 두 줄의 코드 아래위로 삽입해서 실행시켜 보니, `this._closeCallback.call(null)`에서 막히는 것을 확인할 수 있었다. call(null) 형태가 낯설어서 call에 대해 찾아보았다. call은 함수 내부의 this가 다른 객체를 가리키게 하고 싶을 때 쓰는 것인데, 여기서는 null을 넣어주고 있다. 왜 null을 넣는 것인지 이해는 되지 않았지만 일단 this._closeCallback을 찾아보았다.

```javascript
  constructor(connection, contextIds, ignoreHTTPSErrors, defaultViewport, process, closeCallback) {
    super();
    this._ignoreHTTPSErrors = ignoreHTTPSErrors;
    this._defaultViewport = defaultViewport;
    this._process = process;
    this._screenshotTaskQueue = new TaskQueue();
    this._connection = connection;
    this._closeCallback = closeCallback || new Function;
```
browser class의 constructor를 확인해보니 인자로 closeCallback을 받았을 때는 해당 인자를 사용하고, 만약 받지 않았을 경우에는 new Function()이라는 아무일도 하지 않는 익명 함수를 사용하게 되어 있었다.  
node에서 `a = new Function()` 해서 빈 함수를 만든 다음 `a.call(null)`이라고 했을 때 아무 문제도 없었다. `await` 과 `call(null)`을 함께 쓰면 문제가 있나 해서 테스트 해봤지만 역시나 아무일도 없었다.   
아무 내용물도 없는 함수인데, 도대체 뭐가 문제지? 일단 this._closeCallback 함수를 console.log로 찍어봤다. 그랬더니 `fucntion: anonymous function`이 아니라 `function: gracefullyClosechrome`이 출력되었다.  브라우저 인스턴스가 생성될 때 그렇다면 이 `gracefullyClosechrome`함수가 callback으로 주어졌다는 뜻이다.


[puppeteer 문서](https://pptr.dev/)를 열어서 browser 부분을 봤다.  

> “A Browser is created when Puppeteer connects to a Chromium instance, either through puppeteer.launch or puppeteer.connect.” 

버그를 일으키고 있는 코드에서는 launch를 쓰고 있으므로 launch를 조사보기로 했다.   
Puppeteer.js의 launch 메소드는 딱 1줄이다. `this._launcher.launch(options);`   
그리고 이 `this._launcher`는 Launcher.js를 `Launcher`로 받아서 `projectRoot`, `perferredRevision`, `isPuppeteerCore`를 인자로 받아서 만든 것이다. Launcher의 launch 메소드를 쓴 것이기 때문에 Launcher.js를 열어보았다.  

gracefullyclosechorme 함수가 launch 메소드 말미에서 browser를 만들 때 closeCallback 인자로 넘겨지는 것을 확인했다. 

```javascript
const browser = await Browser.create(connection, [], ignoreHTTPSErrors, defaultViewport, chromeProcess, gracefullyCloseChrome);
```

디버거로는 문제가 재현되지 않기 때문에 gracefullyclosechrome 내부에 또다시 console.log를 한줄한줄 넣어봤다. `return waitForChromeToClose` 직전까지는 실행이 잘 되었다. 딱 return 부분에서 멈춘 것이다. `waitForChromeToClose`를 console.log로 찍어보니 `Promise{ <pending> }`이라고 나왔다. `wiatForChormeToClose`는 launch 메소드 안에 있는 프로미스다. 일단 프로미스를 새로 만든 것까지는 성공한 것 같은데, chromeProcess.once부터 전혀 실행이 안 되는 것 같다. 


